### ISSUE TITLE
Downgrade Firefox

### ISSUE THREAD

**Issue by Walskaar** [amirhouieh/instagotwi#1]
Will not run with newest version of Firefox
Does run with "42.0" , not 49

Also, maybe update python with Homebrew

**Comment by amirhouieh** [comment]
I test it with "49.0.1" and still working! I wish you had shared the error logs here. 
from this, i would only guess that it was the Python version or pip!

**Comment by Walskaar** [comment]
Hi Amir
Tested again today  with 49.0.1, did not work for me., will downgrade again and check..

> {u'baseUrl': u'https://www.google.com.sg/search?q=', u'postUrl': u'&tbm=isch', u'selector': u'a.rg_l'}
> google initialized!
> Traceback (most recent call last):
>   File "sample_single_scrape.py", line 3, in <module>
>     gi = scraper.scraper('google')    #source [e.g. "google", "twitter", "instagram"]
>   File "/Users/thomaswalskaar/Documents/_Projects/Lust Workshop/instagotwi-master/scraper/__init__.py", line 60, in **init**
>     self.initializeBrowser()
>   File "/Users/thomaswalskaar/Documents/_Projects/Lust Workshop/instagotwi-master/scraper/__init__.py", line 127, in initializeBrowser
>     self.driver = webdriver.Firefox()
>   File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in **init**
>     self.binary, timeout)
>   File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in **init**
>     self.binary.launch_browser(self.profile, timeout=timeout)
>   File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
>     self._wait_until_connectable(timeout=timeout)
>   File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
>     % (self.profile.path))
> selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/hl/yx_jz_yj1h3937x2bq86vl540000gn/T/tmpJoKxvs If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by Walskaar** [comment]
Works for me with  Firefox 47.0.1
